const {scene,B,DUR}=require('./lib.cjs'); const fs=require('fs'); const path=require('path');
const STATE='state/final.json'; const SHARED='state/shared.json';
const shared=()=>fs.existsSync(SHARED)?JSON.parse(fs.readFileSync(SHARED)):{};
const share=o=>fs.writeFileSync(SHARED,JSON.stringify({...shared(),...o},null,1));
const SLIDES='file:///home/a/code/Vocalis/public/slides.html';
const LOCAL=f=>'file://'+path.resolve('local',f);
async function slide(R,n){ const p=R.page; await p.goto(SLIDES,{waitUntil:'networkidle'}); await p.evaluate(n=>{setTheme('light'); const s=document.createElement('style'); s.textContent='.theme-bar,.nav-bar,.hint{display:none!important} .slide.active{animation:kb 14s ease-out forwards;transform-origin:50% 45%} @keyframes kb{from{transform:scale(1)}to{transform:scale(1.035)}}'; document.head.appendChild(s); showSlide(n);},n); await p.waitForTimeout(500); }
const side=(p,href)=>p.locator(`a[href="${href}"]`).filter({visible:true}).first();

const S={
 async A(){ fs.rmSync(STATE,{force:true});
  await scene('A_landing_onboarding_topics',{state:STATE},async R=>{ const p=R.page;
   await p.goto(B,{waitUntil:'networkidle'}); R.pos={x:1050,y:620}; await p.waitForTimeout(800);
   await R.start(); await R.wait(500);
   let n=R.say('01_hook'); await R.until(n.at(1));
   const hero=p.locator('.hero-actions a').first(); const c=await R.center(hero);
   await R.move(c.x+60,c.y+90,5500); await R.until(n.at(3)); await R.move(c.x,c.y,1800); await R.until(n.end+0.5);
   n=R.say('02_intro'); await R.wait(600); await R.scrollToEl('#how-it-works',40,2200);
   const cards=p.locator('.step-card'); await R.until(n.at(1)-0.4);
   const per=(n.at(2)-n.at(1))/5; for(let i=0;i<5;i++){ await R.hover(cards.nth(i),600); await R.until(n.at(1)+per*(i+1)); }
   await R.move(640,250,1500); await R.until(n.end+0.5);
   n=R.say('03_onboarding'); await R.scrollTo(0,900); await R.click(hero,700);
   R.log('hero clicked'); await p.waitForURL(/onboarding/); await p.getByRole('heading',{name:'What would you like to get better at?'}).waitFor();
   await R.wait(500);
   await R.click(p.getByRole('button',{name:'Speaking confidence',exact:true}),600);
   await R.click(p.getByRole('button',{name:'Thinking on the spot',exact:true}),500);
   await R.click(p.getByRole('button',{name:'Continue',exact:true}),600); await R.wait(500);
   await R.click(p.getByRole('button',{name:/Neutral/}),600);
   await R.click(p.getByRole('button',{name:'Continue',exact:true}),600); await R.wait(400);
   R.log('name'); await R.click(p.getByLabel('What should we call you?'),500); await p.keyboard.press('Control+A'); await p.keyboard.type('Audrius',{delay:70});
   await R.until(n.end-0.3);
   await R.click(p.getByRole('button',{name:'Start Your First Session'}),600);
   R.log('start session clicked'); await p.waitForURL(/\/practice\//); R.log('practice loaded'); await R.wait(900); await R.until(n.end+0.4);
   n=R.say('04_topics'); await R.click(side(p,'/topics'),800); await p.waitForURL(/topics/);
   await p.getByRole('heading',{name:'Find something worth talking about.'}).waitFor(); R.log('topics loaded'); await R.wait(600);
   const card=name=>p.locator('a[href^="/practice/"]').filter({has:p.getByRole('heading',{name,exact:true})}).first();
   await R.hover(card('Everyday Life'),800); await R.wait(500); await R.hover(card('Storytelling'),800); await R.wait(500);
   await R.hover(card('Interview'),900); await R.wait(400);
   await R.until(n.at(1)-2.2); await R.hover(card('Chaotic Mode'),1000); await R.until(n.at(1)+1.2);
   R.log('chaotic done'); await R.scrollTo(0,900); await R.click(p.getByRole('button',{name:'All prompts',exact:true}),700); await R.wait(700);
   const row=p.locator('.topic-row').filter({hasText:'Why are mountains better than beaches?'}).first();
   await R.hover(row.locator('h3'),700); await R.until(n.end-0.4);
   await R.click(row.locator('a,button').filter({hasText:'Try this'}).first(),700);
   await p.waitForURL(/\/practice\//); await p.getByRole('heading',{name:'Why are mountains better than beaches?'}).waitFor(); await R.wait(900); await R.until(n.end+0.3);
   R.end(); share({practiceUrl:p.url(),pos:R.pos});
  }); },
 async B(){ const sh=shared();
  await scene('B_demo_feedback',{state:STATE,mic:'mic/demo.wav'},async R=>{ const p=R.page;
   await p.goto(sh.practiceUrl,{waitUntil:'networkidle'}); await p.getByRole('heading',{name:'Why are mountains better than beaches?'}).waitFor(); R.pos=sh.pos; await p.waitForTimeout(600);
   await R.start(); await R.wait(300);
   let n=R.say('05_before_recording'); await R.wait(700); await R.hover('.session-timer',1200); await R.wait(900);
   const rec=p.getByRole('button',{name:'Start microphone recording'}); await R.hover(rec,1400); await R.until(n.end+0.2);
   await p.mouse.down(); await R.wait(70); await p.mouse.up(); R.mark('rec_click');
   await p.getByRole('button',{name:'Stop recording'}).waitFor({timeout:15000}); R.mark('rec_live');
   await R.wait(1500); await R.move(R.pos.x+230,R.pos.y+40,1200);
   await R.until(R.marks.rec_live+1.5+DUR.dur.mic_demo-0.6);
   await R.hover(p.getByRole('button',{name:'Stop recording'}),1000); await R.until(R.marks.rec_live+1.5+DUR.dur.mic_demo+0.7);
   await p.mouse.down(); await R.wait(70); await p.mouse.up(); R.mark('rec_stop');
   await p.getByRole('heading',{name:'Review your transcript'}).waitFor({timeout:60000});
   await p.waitForFunction(()=>{const t=document.querySelector('textarea');return t&&t.value.trim().split(/\s+/).length>30&&!/Transcribing/.test(document.body.innerText)},null,{timeout:120000}); R.mark('transcribed');
   R.cut(R.marks.rec_stop+1.6,R.marks.transcribed-0.3);
   console.log('  TRANSCRIPT:',await p.locator('textarea').inputValue());
   await R.wait(500); await R.scrollToEl(p.getByRole('heading',{name:'Review your transcript'}),90,1200); await R.wait(1500);
   await R.click(p.getByRole('button',{name:'Analyze my response'}),900); R.mark('analyze');
   await p.waitForURL(/\/session\//,{timeout:90000}); await p.getByRole('heading',{name:'Session complete. Progress made.'}).waitFor(); R.mark('session');
   R.cut(R.marks.analyze+2.0,R.marks.session-0.3);
   await p.evaluate(()=>window.scrollTo(0,0)); await R.wait(900);
   n=R.say('06_feedback'); await R.move(430,350,1500); await R.until(n.at(1)-1.2); await R.scrollTo(190,1100); await R.move(760,410,1200);
   await R.until(n.at(1)+2.5); await R.scrollToEl(p.getByRole('heading',{name:'Delivery & Rhythm Intelligence'}),110,1500);
   for(const t of ['Speaking Pace','Speech Cleanliness','Vocabulary Variety','Signpost Density']){ await R.hover(p.getByText(t,{exact:true}).first(),550); await R.wait(450); }
   await R.hover(p.getByRole('heading',{name:'Your speaking metrics'}),800); await R.scrollToEl(p.getByRole('heading',{name:'Your speaking metrics'}),110,1100);
   await R.until(n.at(2)+0.3); await R.scrollToEl(p.getByRole('heading',{name:'What you did well'}),100,1300); await R.hover(p.getByRole('heading',{name:'What you did well'}),700);
   await R.until(n.at(2)+3.6); await R.scrollToEl(p.getByRole('heading',{name:'Your blunders'}),100,1300); await R.hover(p.getByRole('heading',{name:'Your blunders'}),700);
   await R.until(n.at(3)-1.6); await R.scrollToEl(p.getByRole('heading',{name:'Speech Transcript & Lens'}),150,1700);
   await R.until(n.at(3)+2.2); await R.click(p.getByRole('button',{name:/^Fillers/}),700); await R.wait(1300);
   await R.click(p.getByRole('button',{name:/^Signposts/}),600); await R.wait(1100);
   await R.click(p.getByRole('button',{name:/^Key Terms/}),600); await R.until(n.end+0.5);
   R.end(); share({sessionUrl:p.url(),pos:R.pos,scrollY:await p.evaluate(()=>scrollY)});
  }); },
 async C(){ const sh=shared();
  await scene('C_coach',{state:STATE,mic:'mic/coach.wav'},async R=>{ const p=R.page;
   await p.goto(sh.sessionUrl,{waitUntil:'networkidle'}); await p.getByRole('heading',{name:'Session complete. Progress made.'}).waitFor();
   await p.getByRole('button',{name:/^Key Terms/}).click(); await p.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),sh.scrollY); R.pos=sh.pos; await p.waitForTimeout(700);
   await R.start(); await R.wait(200);
   let n=R.say('07_coach'); await R.wait(500); await R.scrollToEl(p.getByRole('heading',{name:'Small techniques. Big difference.'}),60,2200);
   await R.hover(p.getByRole('heading',{name:'Evidence Integration'}).first(),1100); await R.wait(1500);
   const talk=p.getByRole('button',{name:'Talk with your coach'}); await R.hover(talk,1200); await R.until(n.end-0.9);
   await p.mouse.down(); await R.wait(70); await p.mouse.up(); R.mark('coach_click');
   await R.wait(1500); await R.move(R.pos.x-260,R.pos.y+170,1200);
   const done=()=>{ const u=R.ws.map((x,i)=>x.m.type==='transcript.user'?i:-1).filter(i=>i>=0); if(u.length<2) return false; return R.ws.slice(u[1]).some(x=>x.m.type==='reply.done'&&x.m.status==='completed'); };
   const t0=R.now(); while(!done()&&R.now()-t0<75) await R.wait(250);
   R.mark('coach_done'); await R.wait(1300);
   await R.click(p.getByRole('button',{name:/^End/}),800); await R.wait(700);
   R.end(); share({pos:R.pos,scrollY:await p.evaluate(()=>scrollY)});
  }); },
 async D(){ const sh=shared();
  await scene('D_progress_hackathon',{state:STATE},async R=>{ const p=R.page;
   await p.goto(sh.sessionUrl,{waitUntil:'networkidle'}); await p.getByRole('heading',{name:'Session complete. Progress made.'}).waitFor();
   await p.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),sh.scrollY); R.pos=sh.pos; await p.waitForTimeout(700);
   await R.start(); await R.wait(200);
   let n=R.say('08_progress'); await R.click(side(p,'/progress'),1000); await p.getByRole('heading',{name:'Look how far your voice has come.'}).waitFor(); await R.wait(900);
   await R.scrollToEl(p.getByRole('heading',{name:'Your progress at a glance'}),80,1300); await R.until(n.at(1)+0.3);
   await R.click(p.getByRole('button',{name:'Structure',exact:true}),800); await R.wait(900); await R.click(p.getByRole('button',{name:'Overall',exact:true}).first(),700);
   await R.hover(p.getByRole('heading',{name:'Your latest skill balance'}),800); await R.scrollToEl(p.getByText(/day speaking streak/).first(),330,1300);
   await R.until(n.at(2)-0.6); await R.click(side(p,'/history'),900); await p.waitForURL(/history/); await R.wait(700);
   await R.hover(p.locator('tbody tr').first(),900); await R.until(n.end+0.5);
   n=R.say('09_hackathon'); await R.click(side(p,'/practice'),900); await p.getByRole('heading',{name:'What do you want to talk about?'}).waitFor(); await R.wait(500);
   await R.scrollToEl(p.getByRole('heading',{name:'Hackathon Pitch Training'}),260,1500); await R.until(n.at(1)-0.2);
   await R.click(p.getByRole('link',{name:/Start Pitch Practice/}),900); await p.waitForURL(/hackathon-pitch/); await p.locator('.session-timer').waitFor();
   await R.wait(400); await R.scrollTo(95,900); await R.until(n.at(2)+0.6);
   const len=t=>p.locator('button').filter({hasText:new RegExp('^\\s*'+t+'\\s*$')}).first();
   await R.click(len('1 min'),600); await R.until(n.at(2)+2.4); await R.click(len('3 min'),500); await R.until(n.at(2)+4.3); await R.click(len('5 min'),500);
   await R.until(n.at(3)+0.2); R.end(); share({carry9:n.end-R.now()});
  }); },
 async E(){ const sh=shared();
  await scene('E1_slide4',{cursor:false},async R=>{ await slide(R,4); await R.start(); R.says.push({key:'_carry',t:0}); await R.wait((sh.carry9+0.6)*1000); R.end(); });
  await scene('E2_graphic',{cursor:false},async R=>{ const p=R.page; await p.goto(LOCAL('graphic.html'),{waitUntil:'networkidle'}); await p.waitForTimeout(500);
   await R.start(); await R.wait(400); const n=R.say('10_assemblyai'); await p.evaluate(()=>step(1)); await R.wait(1500); await p.evaluate(()=>step(2)); await R.wait(2200); await p.evaluate(()=>step(3));
   await R.until(n.at(1)+0.2); R.end(); share({t10:n.t,cut10:R.now()}); });
  const s2=shared();
  await scene('E3_slide5',{cursor:false},async R=>{ await slide(R,5); await R.start(); await R.wait((DUR.off['10_assemblyai'][2]-DUR.off['10_assemblyai'][1])*1000); R.end(); });
  await scene('E4_graphic2',{cursor:false},async R=>{ const p=R.page; await p.goto(LOCAL('graphic.html'),{waitUntil:'networkidle'}); await p.evaluate(()=>all()); await p.waitForTimeout(500);
   const o=DUR.off['10_assemblyai'], d=DUR.dur['10_assemblyai']; await R.start(); const t=i=>o[i]-o[2];
   await R.wait(900); await p.evaluate(()=>focus3()); await R.until(t(3)-0.5); await p.evaluate(()=>tagline()); await R.until(t(4)+1.3); await p.evaluate(()=>github()); await R.until(d-o[2]+3.2); R.end(); });
 },
 async F(){ const o=DUR.off['11_business'], d=DUR.dur['11_business'];
  await scene('F1_landing',{state:STATE},async R=>{ const p=R.page; await p.goto(B,{waitUntil:'networkidle'}); R.pos={x:900,y:420}; await p.waitForTimeout(800);
   await R.start(); await R.wait(500); const n=R.say('11_business'); share({f1:n.t}); await R.wait(900);
   const h=await p.evaluate(()=>document.documentElement.scrollHeight); share({landH:h});
   await R.scrollTo(Math.round(h*0.42),(o[1]-1.2)*1000); await R.until(n.at(1)+0.1); R.end(); share({landY:await p.evaluate(()=>scrollY)}); });
  await scene('F2_slide7',{cursor:false},async R=>{ await slide(R,7); await R.start(); await R.wait((o[2]-o[1])*1000); R.end(); });
  const sh=shared();
  await scene('F3_landing_bottom',{state:STATE},async R=>{ const p=R.page; await p.goto(B,{waitUntil:'networkidle'}); await p.evaluate(y=>window.scrollTo({top:y+500,behavior:'instant'}),sh.landY); R.pos={x:900,y:420}; await p.waitForTimeout(900);
   await R.start(); const tot=d-o[2]+0.7; await R.scrollToEl('.bottom-cta',110,(tot-2.2)*1000); await R.hover(p.locator('.bottom-cta a').first(),1200); await R.until(tot); R.end(); });
 },
 async G(){ await scene('G_logo',{cursor:false},async R=>{ const p=R.page; await p.goto(LOCAL('logo.html'),{waitUntil:'networkidle'}); await p.waitForTimeout(400);
   await R.start(); await R.wait(300); await p.evaluate(()=>showLogo()); await R.wait(500); const n=R.say('12_final'); await R.until(n.at(3)-0.3); await p.evaluate(()=>showTag()); await R.until(n.end+3.2); R.end(); }); },
};
(async()=>{ for(const k of process.argv.slice(2)){ console.log('=== scene group',k); await S[k](); } })().catch(e=>{console.error(e);process.exit(1)});
