'use client';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Mic, Flame, Clock3, Target, TrendingUp, Sparkles, Check, AudioLines, Info } from 'lucide-react';
import { useVocalis, getStats } from '@/hooks/use-vocalis';
import { categories } from '@/data/topics';
import { ButtonLink, CategoryCard, PageHeading, StatCard, Waveform } from './ui';
import ProgressChart from './progress-chart';
import ChaosChallenge from './chaos-challenge';
import { Session } from '@/types';
export function WeeklyCalendar({sessions}:{sessions:Session[]}){
 const today=new Date();const monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7));const dates=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return d;});
 return <div className="week-calendar" aria-label="This week’s speaking practice">{dates.map((d,i)=>{const complete=sessions.some(s=>new Date(s.date).toDateString()===d.toDateString());const isToday=d.toDateString()===today.toDateString();return <div key={i} className={`week-day ${complete?'complete':''} ${isToday?'today':''}`}><span aria-label={`${d.toLocaleDateString(undefined,{weekday:'long'})}: ${complete?'practiced':'not practiced'}${isToday?', today':''}`}>{complete?<Check size={13}/>:d.getDate()}</span>{['M','T','W','T','F','S','S'][i]}</div>;})}</div>;
}
export default function Dashboard(){
 const {data,clearDemo}=useVocalis();const stats=getStats(data.sessions);const latest=data.sessions.at(-1);const focus=latest?.analysis.weak_areas[0]?.name|| (data.profile.goals.includes('Thinking on the spot')?'Spontaneity':'Structure');
 const suggested=data.profile.goals.includes('Interviews')?'interview':data.profile.goals.includes('Storytelling')?'storytelling':'everyday-life';
 return <><PageHeading label="A LITTLE PRACTICE. A STRONGER VOICE." title={`Good to see you, ${data.profile.name||'speaker'}.`} description="Big ideas start with small moments of practice. Let’s make yours count." action={<ButtonLink href="/practice">Start practice <Mic size={15}/></ButtonLink>}/>
 {data.sessions.some(s=>s.demo)&&<div className="demo-banner"><Info size={13}/><span>You’re exploring sample progress. Your real sessions will be saved right here.</span><button onClick={clearDemo}>Clear sample data</button></div>}
 <section className="welcome-banner"><div><div className="eyebrow"><span/>YOUR NEXT SPEAKING MOMENT</div><h2>Your voice has something to say.</h2><p>One prompt. Sixty seconds. A little more confidence.</p><ButtonLink href={`/practice/${suggested}`}>Let’s hear it <ArrowUpRight size={16}/></ButtonLink></div><div className="welcome-art"><Waveform/><span className="mic-orb"><Mic size={32}/></span></div></section>
 <ChaosChallenge/>
 <div className="stats-grid"><StatCard icon={Flame} label="Current streak" value={`${stats.streak} days`} detail="Consistency over perfection"/><StatCard icon={AudioLines} label="Sessions completed" value={data.sessions.length} detail={`${stats.minutes} minutes of showing up`}/><StatCard icon={Clock3} label="Speaking time" value={`${stats.minutes} min`} detail="Every minute makes a difference"/><StatCard icon={Target} label="Average score" value={stats.average||'—'} detail={`${stats.improvement>=0?'+':''}${stats.improvement} points since your first session`} positive/></div>
 <div className="dashboard-columns"><section className="panel"><div className="panel-heading"><div><h2>Small steps. Real progress.</h2><p>Your overall speaking score</p></div><span className="subtle-tag">Last {Math.min(data.sessions.length,10)} sessions</span></div><ProgressChart sessions={data.sessions.slice(-10)}/><div className="chart-summary"><TrendingUp size={14}/><span>{data.sessions.length>1?<><b>{stats.improvement>=0?'+':''}{stats.improvement} points</b> since your first session. You’re finding your rhythm.</>:'Your first session is the beginning of your progress.'}</span><Link href="/progress" aria-label="View all progress" style={{marginLeft:'auto'}}><ArrowUpRight size={14}/></Link></div></section><section className="panel focus-panel"><div className="focus-icon"><Sparkles size={17}/>YOUR FOCUS</div><h3>Your next opportunity?<br/><em>{focus}.</em></h3><p>{latest?.analysis.weak_areas[0]?.detail||'Give your ideas a clear beginning, middle, and end. A simple framework makes it easier to think on your feet.'}</p><div className="focus-technique">{latest?.analysis.improvement_techniques[0]?.name||'Point → Reason → Example → Conclusion'}</div><Link href={`/practice/${suggested}`} className="text-link">Put it into practice <ArrowRight size={14}/></Link></section></div>
 <div className="section-title-row"><h2>What’s on your mind?</h2><Link href="/practice" className="text-link">Explore all categories <ArrowRight size={14}/></Link></div><div className="dashboard-categories">{[suggested,suggested==='storytelling'?'opinions':'storytelling','random'].map(id=><CategoryCard key={id} compact category={categories.find(c=>c.id===id)!}/>)}</div>
 <section className="panel streak-panel"><div className="streak-title"><Flame size={28}/><div><h3>{stats.streak} day speaking streak</h3><p>Keep showing up. Your future self will thank you.</p></div></div><WeeklyCalendar sessions={data.sessions}/></section>
 <div className="section-title-row"><h2>Your speaking snapshot</h2><Link href="/profile" className="text-link">View your profile <ArrowRight size={14}/></Link></div><div className="stats-grid" style={{gridTemplateColumns:'repeat(2,1fr)'}}><StatCard icon={TrendingUp} label="Strongest skill" value={stats.strongest} detail="Keep building on what comes naturally" positive/><StatCard icon={Sparkles} label="Current focus" value={stats.weakest} detail="One specific improvement at a time"/></div>
 </>;
}
