'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Play, Mic, Sparkles, Check, ChevronRight, AudioLines, Target, TrendingUp, X, Menu, Quote, ShieldCheck, Clock3, Zap } from 'lucide-react';
import { Logo, ButtonLink, Eyebrow, Waveform, CategoryCard, CheckLine } from './ui';
import { categories } from '@/data/topics';
import { useDialogAccessibility } from '@/hooks/use-dialog';
export default function Landing(){
 const [video,setVideo]=useState(false);const [menu,setMenu]=useState(false);
 useDialogAccessibility(video,()=>setVideo(false));
 return <div className="landing">
 <header className="landing-header"><div className="landing-nav"><Logo/><nav aria-label="Main navigation" className={menu?'mobile-open':''}><Link href="#how-it-works" onClick={()=>setMenu(false)}>How it works</Link><Link href="#explore" onClick={()=>setMenu(false)}>Explore topics</Link><Link href="#why-vocalis" onClick={()=>setMenu(false)}>Why Vocalis</Link></nav><div className="nav-actions"><Link className="login-link" href="/dashboard">Log in <ArrowUpRight size={14}/></Link><ButtonLink href="/onboarding">Start speaking <ArrowRight size={16}/></ButtonLink><button className="icon-button mobile-toggle" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main>
 <section className="hero section-container">
 <div className="hero-copy"><Eyebrow>A LITTLE PRACTICE. A MORE CONFIDENT YOU.</Eyebrow><h1>Speak Better.<br/><em>Think Faster.</em></h1><p className="hero-description">Your next big idea deserves to be heard.<br className="desktop-break"/> Practice spontaneous speaking and turn everyday<br className="desktop-break"/> thoughts into confident words—with your AI coach.</p><div className="hero-actions"><ButtonLink href="/onboarding">Start Speaking <ArrowUpRight size={19}/></ButtonLink><button className="button button-secondary" onClick={()=>setVideo(true)}><span className="play-icon"><Play size={13} fill="currentColor"/></span>See how it works</button></div><div className="hero-checks"><CheckLine>Just 60 seconds a day</CheckLine><CheckLine>No pressure. Just progress.</CheckLine></div><div className="social-proof"><div className="avatar-stack"><span className="avatar av-1">JL</span><span className="avatar av-2">AK</span><span className="avatar av-3">MR</span><span className="avatar av-4">TS</span></div><div><div className="five-stars">★★★★★</div><p>For big ideas. And everyday conversations.</p></div></div></div>
 <div className="hero-visual"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="visual-spark spark-one">✳</div><div className="visual-spark spark-two">+</div><div className="floating-label"><span><Sparkles size={14}/></span>Your voice. Your potential.</div>
 <div className="speaking-preview"><div className="preview-header"><span><span className="live-dot"/> YOUR DAILY SPEAKING MOMENT</span><span className="preview-timer"><Clock3 size={13}/>60 sec</span></div><div className="preview-topic"><span className="tiny-label">LET’S TALK ABOUT</span><h2>Why are mountains<br/>better than beaches?</h2><span className="topic-tag">Everyday Life <span>·</span> Beginner</span></div><div className="preview-wave"><Waveform active/><div className="wave-baseline"/></div><div className="preview-record"><span className="record-side">YOUR VOICE<br/><b>One minute. All you.</b></span><Link className="preview-mic" aria-label="Practice this speaking prompt" href="/practice/everyday-life?prompt=Why%20are%20mountains%20better%20than%20beaches%3F"><Mic size={27}/></Link><span className="record-side right-side">NO PERFECT ANSWERS<br/><b>Just press record.</b></span></div><div className="preview-footer"><span className="mini-spark"><Sparkles size={13}/></span>A safe space to find your voice.</div></div>
 <div className="floating-score"><div className="small-score-ring"><span>82<small>/100</small></span><svg viewBox="0 0 60 60"><circle cx="30" cy="30" r="25" fill="none" stroke="#e8eee7" strokeWidth="4"/><circle cx="30" cy="30" r="25" fill="none" stroke="#77987a" strokeWidth="4" strokeDasharray="128 157" transform="rotate(-90 30 30)" strokeLinecap="round"/></svg></div><div><strong>A little better, every day.</strong><span><TrendingUp size={12}/> +12 points in clarity</span></div><div className="sample-label">SAMPLE INSIGHT</div></div>
 <div className="floating-coach"><span className="coach-star"><Sparkles size={18}/></span><div><strong>Good ideas. Even better delivery.</strong><p>Let’s make your next answer more structured.</p></div><Check size={16}/></div>
 </div>
 </section>
 <section className="benefit-strip"><div className="section-container"><p>A small daily habit.<br/><strong>A real-world difference.</strong></p><span><Mic size={21}/>Speak with confidence</span><span><Zap size={21}/>Think on your feet</span><span><MessagesIcon/>Make your words count</span><span><TrendingUp size={21}/>Grow with every session</span></div></section>
 <section id="how-it-works" className="how-section section-container"><div className="section-heading"><div><Eyebrow>ONE MINUTE. FIVE SIMPLE STEPS.</Eyebrow><h2>Find your voice.<br className="mobile-break"/> <span>Then make it stronger.</span></h2></div><p>No scripts. No perfect answers.<br/>Just you, a prompt, and a little progress.</p></div><div className="steps-grid">{[{n:'01',icon:Target,title:'Choose',text:'Pick a topic that sparks your curiosity.'},{n:'02',icon:Mic,title:'Speak',text:'Think on your feet. Speak for 60 seconds.'},{n:'03',icon:AudioLines,title:'Analyze',text:'Get a clear picture of how you communicate.'},{n:'04',icon:Sparkles,title:'Improve',text:'Turn specific feedback into practical techniques.'},{n:'05',icon:TrendingUp,title:'Repeat',text:'Build your streak. Watch your confidence grow.'}].map((s,i)=><div className="step-card" key={s.n}><div className="step-top"><span className={`step-icon ${i===1?'active':''}`}><s.icon size={21}/></span><span className="step-number">{s.n}</span>{i<4&&<ChevronRight className="step-chevron" size={15}/>}</div><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></section>
 <section id="explore" className="explore-section"><div className="section-container"><div className="section-heading"><div><Eyebrow>FOLLOW YOUR CURIOSITY</Eyebrow><h2>A topic for every side of you.</h2><p>From everyday stories to wonderfully unexpected questions.</p></div><Link className="text-link" href="/topics">Explore all 17 categories <ArrowRight size={17}/></Link></div><div className="landing-categories">{['everyday-life','storytelling','interview','chaotic'].map(id=><CategoryCard key={id} category={categories.find(c=>c.id===id)!}/>)}</div><div className="topic-bottom"><ShuffleIcon/><span>Not sure where to start? Let a little randomness lead the way.</span><Link href="/practice/random">Surprise me <ArrowUpRight size={15}/></Link></div></div></section>
 <section id="why-vocalis" className="why-section section-container"><div className="why-visual"><div className="coach-card"><div className="coach-card-label"><Sparkles size={18}/> YOUR VOCALIS COACH <span>PERSONALIZED FEEDBACK</span></div><Quote size={30} className="quote-icon"/><h3>Your ideas are strong.<br/>Let’s give them a little structure.</h3><p>Your response had a clear point of view. An example would help your audience see what you mean.</p><div className="technique-mini"><span>TRY THIS NEXT TIME</span><strong>Point <ArrowRight/> Reason <ArrowRight/> Example <ArrowRight/> Conclusion</strong></div><span className="sample-note">Illustrative coaching preview</span></div></div><div className="why-copy"><Eyebrow>MORE THAN A SCORE</Eyebrow><h2>Know what to improve.<br/><em>And exactly how.</em></h2><p>“Just be more confident” isn’t coaching. Vocalis helps you understand your patterns and gives you something concrete to try next.</p><div className="why-list"><div><span><Check size={15}/></span><p><strong>Feedback that gets specific</strong>Discover your strengths, filler words, and blind spots.</p></div><div><span><Check size={15}/></span><p><strong>Techniques you can actually use</strong>Simple frameworks. Clear examples. A plan for next time.</p></div><div><span><Check size={15}/></span><p><strong>Your progress, made visible</strong>See the small improvements that add up over time.</p></div></div><ButtonLink href="/onboarding">Find your speaking potential <ArrowUpRight size={18}/></ButtonLink></div></section>
 <section className="bottom-cta section-container"><div className="cta-decoration"><AudioLines/></div><Eyebrow>YOUR VOICE IS WORTH THE PRACTICE</Eyebrow><h2>Your next breakthrough<br/>is <em>one minute away.</em></h2><p>You don’t need the perfect words. You just need to start.</p><ButtonLink href="/onboarding">Start Speaking <ArrowUpRight size={19}/></ButtonLink><span className="cta-note"><ShieldCheck size={14}/>No account required. Your progress stays in your browser.</span></section>
 </main><footer className="landing-footer section-container"><Logo/><p>A little practice. A stronger voice.</p><div><Link href="/profile">Your data & privacy</Link><span>© {new Date().getFullYear()} Vocalis</span></div></footer>
 {video&&<div className="modal-overlay" onClick={()=>setVideo(false)}><section className="modal how-modal" role="dialog" aria-modal="true" aria-labelledby="how-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setVideo(false);}}><button autoFocus className="icon-button modal-close" aria-label="Close introduction" onClick={()=>setVideo(false)}><X/></button><span className="icon-box orange"><Mic/></span><h2 id="how-title">One minute can change<br/>how you communicate.</h2><p>Choose a topic, record your response, then review your transcript. Vocalis turns your speaking patterns into practical coaching.</p><div className="modal-demo"><Waveform active/><span>Explore a complete sample session—no microphone needed.</span></div><ButtonLink href="/practice/everyday-life?demo=true">Try the interactive demo <ArrowRight size={17}/></ButtonLink><button className="text-button" onClick={()=>setVideo(false)}>Keep exploring</button></section></div>}
 </div>;
}
function MessagesIcon(){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5Z"/></svg>;}
function ShuffleIcon(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="m18 14 4 4-4 4m0-20 4 4-4 4M2 18h2c6 0 8-12 14-12h4M2 6h2c3 0 5 3 7 6s4 6 7 6h4"/></svg>;}
