'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, Check, Mic, ShieldCheck, Sparkles } from 'lucide-react';
import { Logo } from './ui';
import { goals, comfortLevels } from '@/data/topics';
import { useVocalis } from '@/hooks/use-vocalis';
export default function Onboarding(){
 const {data,updateProfile}=useVocalis();const router=useRouter();const [step,setStep]=useState(0);const [selected,setSelected]=useState<string[]>([]);const [comfort,setComfort]=useState('');const [name,setName]=useState('');
 function finish(){updateProfile({name:name.trim()||data.profile.name||'Speaker',goals:selected,comfort,onboarded:true});const category=selected.includes('Interviews')?'interview':selected.includes('Storytelling')?'storytelling':comfort.includes('uncomfortable')?'everyday-life':selected.includes('Persuasion')?'debate':'opinions';router.push(`/practice/${category}`);}
 return <div className="onboarding"><header className="onboarding-header"><Logo/><Link href="/dashboard">Explore the dashboard <ArrowRight size={12} style={{display:'inline',marginLeft:5}}/></Link></header><main className="onboarding-card"><div className="onboarding-progress" aria-label={`Step ${step+1} of 3`}>{[0,1,2].map(n=><span className={n<=step?'active':''} key={n}/>)}</div><span className="onboarding-step">LET’S MAKE THIS YOURS · 0{step+1} / 03</span><h1>{['What would you like to get better at?','How does thinking on your feet feel?','A stronger voice starts with you.'][step]}</h1><p>{['Pick the skills you want to build. We’ll help you turn them into a daily practice.','There’s no right answer. This just helps us find your starting point.','Tell us what to call you, and we’ll get your first speaking moment ready.'][step]}</p>
 {step===0&&<div className="goal-options">{goals.map(goal=><button aria-pressed={selected.includes(goal)} className={`goal-option ${selected.includes(goal)?'selected':''}`} key={goal} onClick={()=>setSelected(old=>old.includes(goal)?old.filter(g=>g!==goal):[...old,goal])}><span className="option-check">{selected.includes(goal)&&<Check size={12}/>}</span>{goal}</button>)}</div>}
 {step===1&&<div className="comfort-options">{comfortLevels.map((level,i)=><button aria-pressed={comfort===level} className={`goal-option ${comfort===level?'selected':''}`} key={level} onClick={()=>setComfort(level)}><span aria-hidden="true">{['◔','◑','◕','◉','✳'][i]}</span>{level}<span className="option-check">{comfort===level&&<Check size={11}/>}</span></button>)}</div>}
 {step===2&&<><label className="form-label" htmlFor="name">What should we call you?</label><input id="name" className="form-input name-input" placeholder="Your first name" maxLength={40} value={name} onChange={e=>setName(e.target.value)} autoComplete="given-name"/><div className="personalized-plan"><h3><Sparkles size={16}/>Your personalized starting point</h3><p><b>Your focus:</b> {selected.join(' · ')}</p><p><b>Your pace:</b> {comfort.includes('uncomfortable')?'Approachable prompts, a simple structure, and no pressure.':'Fresh perspectives and prompts that stretch your thinking.'}</p><p><b>Your commitment:</b> Just one minute. We’ll take it from there.</p></div></>}
 <div className="onboarding-actions">{step>0?<button className="text-button" onClick={()=>setStep(step-1)}><ArrowLeft size={13} style={{display:'inline',marginRight:6}}/>Back</button>:<span>Select one or more</span>}<button className="button button-primary" disabled={step===0?!selected.length:step===1?!comfort:!name.trim()} onClick={()=>step===2?finish():setStep(step+1)}>{step===2?'Start Your First Session':'Continue'}{step===2?<Mic size={16}/>:<ArrowRight size={16}/>}</button></div><div className="onboarding-privacy"><ShieldCheck size={12}/>Your practice space is personal. No account required.</div></main></div>;
}
