import { Session, Metric } from '@/types';
export default function ProgressChart({sessions,metric='Overall',large=false}:{sessions:Session[];metric?:Metric|'Overall';large?:boolean}){
 const sorted=[...sessions].sort((a,b)=>a.date.localeCompare(b.date));const values=sorted.map(s=>metric==='Overall'?s.analysis.overall_score:s.analysis.metrics[metric]);
 const width=560,height=large?245:210;const left=31,right=18,top=22,bottom=33;const chartHeight=height-top-bottom;
 const points=values.map((v,i)=>({x:left+(values.length===1?(width-left-right)/2:i/Math.max(1,values.length-1)*(width-left-right)),y:top+(100-v)/100*chartHeight}));
 const line=points.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ');
 const area=points.length?`${line} L${points.at(-1)!.x},${height-bottom} L${points[0].x},${height-bottom} Z`:'';
 return <div className="chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metric} scores: ${values.join(', ')||'No sessions yet'}`}><defs><linearGradient id={`chartFill-${metric}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e9a06e" stopOpacity=".16"/><stop offset="100%" stopColor="#e9a06e" stopOpacity="0"/></linearGradient></defs>{[0,25,50,75,100].map(n=><g key={n}><line className="chart-grid" x1={left} x2={width-right} y1={top+(100-n)/100*chartHeight} y2={top+(100-n)/100*chartHeight}/><text className="chart-label" x={0} y={top+(100-n)/100*chartHeight+3}>{n}</text></g>)}{area&&<path d={area} fill={`url(#chartFill-${metric})`}/>}<path d={line} className="chart-line"/>{points.map((p,i)=><g key={sorted[i].id}><circle className="chart-dot" cx={p.x} cy={p.y} r={i===points.length-1?4.5:3}><title>{new Date(sorted[i].date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}: {values[i]} / 100</title></circle>{(points.length<9||i===0||i===points.length-1||i%Math.ceil(points.length/6)===0)&&<text className="chart-label" textAnchor="middle" x={p.x} y={height-9}>{new Date(sorted[i].date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</text>}{i===points.length-1&&<g><rect x={p.x-16} y={p.y-27} width={32} height={18} rx={4} fill="#f8eee2"/><text x={p.x} y={p.y-15} textAnchor="middle" style={{fontSize:10,fill:'#c28c58',fontFamily:'var(--font-body)',fontWeight:600}}>{values[i]}</text></g>}</g>)}{!points.length&&<text x={width/2} y={height/2} textAnchor="middle" className="chart-label">Your first session starts your progress story.</text>}</svg></div>;
}
