'use client';
import { useState } from 'react';
import { Flame, AudioLines, Clock3, Target, TrendingUp, ArrowUpRight, Sparkles, Award, Info } from 'lucide-react';
import { useVocalis, getStats } from '@/hooks/use-vocalis';
import { PageHeading, ButtonLink, StatCard, EmptyState } from './ui';
import { WeeklyCalendar } from './dashboard';
import ProgressChart from './progress-chart';
import { Metric } from '@/types';
export default function ProgressPage(){
 const {data}=useVocalis();const [range,setRange]=useState('7 days');const [metric,setMetric]=useState<Metric|'Overall'>('Overall');const stats=getStats(data.sessions);
 const boundary=new Date();boundary.setHours(0,0,0,0);boundary.setDate(boundary.getDate()-(range==='7 days'?6:29));
 const filtered=data.sessions.filter(s=>range==='All time'||new Date(s.date)>=boundary).sort((a,b)=>a.date.localeCompare(b.date));const filteredStats=getStats(filtered);const first=filtered[0],last=filtered.at(-1);const metricValue=(s:typeof first)=>metric==='Overall'?s.analysis.overall_score:s.analysis.metrics[metric];
 const levels=['Beginner','Developing','Confident','Advanced','Exceptional'];const currentLevel=levels.indexOf(stats.level);
 return <><PageHeading label="SMALL STEPS ADD UP" title="Look how far your voice has come." description="Progress isn’t always a straight line. Showing up is what moves it forward." action={<ButtonLink href="/practice">Keep practicing <ArrowUpRight size={15}/></ButtonLink>}/>{data.sessions.some(s=>s.demo)&&<div className="demo-banner"><Info size={13}/><span>Sample sessions are included in these trends. You can clear them from your dashboard or profile.</span></div>}<div className="panel-heading"><h2>Your progress at a glance</h2><div className="segmented">{['7 days','30 days','All time'].map(r=><button className={range===r?'active':''} key={r} onClick={()=>setRange(r)}>{r}</button>)}</div></div><div className="stats-grid"><StatCard icon={Flame} label="Current streak" value={`${stats.streak} days`} detail="Your all-time practice rhythm"/><StatCard icon={AudioLines} label="Sessions" value={filtered.length} detail={`In the ${range==='All time'?'full':'selected'} period`}/><StatCard icon={Clock3} label="Speaking time" value={`${filteredStats.minutes} min`} detail="Time invested in your voice"/><StatCard icon={Target} label="Average score" value={filteredStats.average||'—'} detail={`${filteredStats.improvement>=0?'+':''}${filteredStats.improvement} points in this period`} positive/></div>
 {!filtered.length?<EmptyState title="A fresh chapter starts here." description="There are no sessions in this period. Try another date range, or make a little time for your voice today."/>:<div className="progress-layout"><section className="panel progress-chart-panel"><div className="panel-heading"><div><h2>Your voice, over time</h2><p>Coaching indicators · {range.toLowerCase()}</p></div><span className="subtle-tag">{metric}</span></div><div className="metric-select">{(['Overall','Clarity','Structure','Fluency','Vocabulary','Spontaneity','Conciseness'] as const).map(m=><button className={metric===m?'active':''} onClick={()=>setMetric(m)} key={m}>{m}</button>)}</div><ProgressChart sessions={filtered} metric={metric} large/>{first&&last&&filtered.length>1&&<div className="chart-summary"><TrendingUp size={15}/><span><b>{metric} {metricValue(last)>=metricValue(first)?'improved':'changed'} from {metricValue(first)} → {metricValue(last)}</b> over {filtered.length} sessions.</span></div>}<p className="muted-note">These are practice indicators, not scientific measurements. Different prompts and durations can affect your scores.</p></section><section className="panel"><div className="panel-heading"><div><h2>Your latest skill balance</h2><p>From your most recent session in this period</p></div></div>{last&&Object.entries(last.analysis.metrics).map(([name,value])=><div className="metric-row" key={name}><div><span>{name}</span><b>{value}</b></div><div className={`metric-track ${value<75?'orange-track':''}`}><span style={{width:`${value}%`}}/></div></div>)}</section></div>}
 <section className="panel streak-panel"><div className="streak-title"><Flame size={30}/><div><h3>{stats.streak} day speaking streak</h3><p>A little consistency goes a long way. Here’s your week.</p></div></div><WeeklyCalendar sessions={data.sessions}/></section><div className="dashboard-columns" style={{marginTop:22}}><section className="panel level-panel"><div className="focus-icon"><Award size={18}/>YOUR SPEAKING JOURNEY</div><h3>{stats.level} speaker</h3><p>A milestone in your practice journey—not a certification. Keep building your sessions and refining your technique.</p><div className="level-progress">{levels.map((l,i)=><span key={l} className={i<=currentLevel?'achieved':''}/>)}</div><div className="level-labels">{levels.map(l=><span key={l}>{l}</span>)}</div><p className="muted-note">Start with 5 sessions, then build a 70+ average for Confident, 80+ for Advanced, and 90+ for Exceptional.</p></section><section className="panel focus-panel"><div className="focus-icon"><Sparkles size={16}/>ONE THING TO TRY NEXT</div><h3>{last?.analysis.improvement_techniques[0]?.name||'Point → Reason → Example → Conclusion'}</h3><p>{last?.analysis.improvement_techniques[0]?.practice||'Answer a fresh prompt in four parts. A point, a reason, an example, and a conclusion.'}</p><ButtonLink href="/practice" secondary>Turn insight into practice <ArrowUpRight size={14}/></ButtonLink></section></div>
 </>;
}
