'use client';
import { useState } from 'react';
import { Search, ArrowUpRight, Sparkles, Check, Shuffle, ChevronDown } from 'lucide-react';
import { categories, nextDifficulty } from '@/data/topics';
import { useVocalis } from '@/hooks/use-vocalis';
import { ButtonLink, PageHeading, CategoryCard, iconMap, EmptyState } from './ui';
import PitchRoadmap from './pitch-roadmap';
import ChaosChallenge from './chaos-challenge';
const levels=[{id:'Beginner',title:'Beginner',description:'Warm up with familiar topics'},{id:'Intermediate',title:'Intermediate',description:'Tell stories and explain ideas'},{id:'Advanced',title:'Advanced',description:'Argue, lead and think in depth'},{id:'Chaotic',title:'A little chaos',description:'No preparation, think on your feet'}] as const;
export default function TopicLibrary({practice=false}:{practice?:boolean}){
 const {data}=useVocalis();const [search,setSearch]=useState('');const [difficulty,setDifficulty]=useState('All difficulties');const [category,setCategory]=useState('All categories');const [status,setStatus]=useState('All prompts');const [view,setView]=useState<'categories'|'prompts'>('categories');const [collapsed,setCollapsed]=useState<string[]>([]);
 const practiced=new Set(data.sessions.filter(ss=>!ss.demo).map(ss=>ss.topic.replace(/^ARGUE (FOR|AGAINST): /,'')));
 const toggleLevel=(id:string)=>setCollapsed(c=>c.includes(id)?c.filter(l=>l!==id):[...c,id]);
 const filtered=categories.filter(c=>(category==='All categories'||category===c.id)&&(difficulty==='All difficulties'||c.difficulty===difficulty)&&(c.name+' '+c.description).toLowerCase().includes(search.toLowerCase()));
 const prompts=categories.filter(c=>(category==='All categories'||category===c.id)&&(difficulty==='All difficulties'||c.difficulty===difficulty)).flatMap(c=>c.prompts.map((prompt,i)=>({category:c,prompt,id:`${c.id}-${i}`,completed:data.sessions.some(s=>s.topic===prompt)}))).filter(p=>(p.prompt+' '+p.category.name).toLowerCase().includes(search.toLowerCase())&&(status==='All prompts'||(status==='Completed'?p.completed:!p.completed)));
 const showPrompts=!practice&&(view==='prompts'||status!=='All prompts');
 return <><PageHeading label={practice?'YOUR NEXT SPEAKING MOMENT':'A LITTLE CURIOSITY GOES A LONG WAY'} title={practice?'What do you want to talk about?':'Find something worth talking about.'} description={practice?'Follow your curiosity. Choose a category and let your voice take it from there.':'Explore prompts that make you think, feel, and see things a little differently.'} action={<ButtonLink href="/practice/random"><Shuffle size={15}/>Surprise me</ButtonLink>}/>
 <div className="level-hint"><Sparkles size={14}/><span>{nextDifficulty(data.sessions.filter(s=>!s.demo).length)} prompts recommended for your current practice level. <b>Challenge yourself when you’re ready.</b></span></div>
 <div className="filter-bar"><div className="search-field"><Search/><input aria-label="Search topics and categories" placeholder={practice?'Search categories…':'Search topics or categories…'} value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter by difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['All difficulties','Beginner','Intermediate','Advanced','Chaotic'].map(d=><option key={d}>{d}</option>)}</select>{!practice&&<><select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)}><option>All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Filter by completion" value={status} onChange={e=>setStatus(e.target.value)}>{['All prompts','Completed','Uncompleted'].map(s=><option key={s}>{s}</option>)}</select></>}</div>
 {!practice&&<div className="panel-heading"><span style={{fontSize:10,color:'var(--muted)'}}>{showPrompts?`${prompts.length} prompts to explore`:`${filtered.length} categories · ${categories.reduce((n,c)=>n+c.prompts.length,0)} prompts`}</span><div className="segmented"><button className={!showPrompts?'active':''} onClick={()=>{setView('categories');setStatus('All prompts');}}>Categories</button><button className={showPrompts?'active':''} onClick={()=>setView('prompts')}>All prompts</button></div></div>}
 {practice&&<div className="pill-filters">{['All difficulties','Beginner','Intermediate','Advanced','Chaotic'].map(d=><button key={d} className={`filter-pill ${difficulty===d?'active':''}`} onClick={()=>setDifficulty(d)}>{d==='All difficulties'?'All categories':d==='Chaotic'?'A little chaos':d}</button>)}</div>}
 {showPrompts?<div className="topic-list">{prompts.map(p=>{const Icon=iconMap[p.category.icon];return <article className="panel topic-row" key={p.id}><span className={`icon-box ${p.category.color}`}><Icon size={19}/></span><div><h3>{p.prompt}</h3><div className="session-meta"><span>{p.category.name}</span><span className={`difficulty ${p.category.difficulty.toLowerCase()}`}><i/>{p.category.difficulty}</span>{p.completed&&<span className="topic-done"><Check size={10}/>Practiced</span>}</div></div><ButtonLink href={`/practice/${p.category.id}?prompt=${encodeURIComponent(p.prompt)}`} secondary>Try this <ArrowUpRight size={13}/></ButtonLink></article>;})}{!prompts.length&&<EmptyState title="A fresh perspective is one filter away." description="No prompts match these filters. Try another category or clear your search."/>}</div>:practice&&filtered.length?<div className="level-groups">{levels.map(level=>{const group=filtered.filter(c=>c.difficulty===level.id);const open=!collapsed.includes(level.id);const total=group.reduce((n,c)=>n+c.prompts.length,0);const done=group.reduce((n,c)=>n+c.prompts.filter(p=>practiced.has(p)).length,0);return group.length?<section key={level.id} className="level-group" aria-labelledby={`level-${level.id}`}><button type="button" className="level-group-head" aria-expanded={open} aria-controls={`level-grid-${level.id}`} onClick={()=>toggleLevel(level.id)}><h2 id={`level-${level.id}`} className={`difficulty ${level.id.toLowerCase()}`}><i/>{level.title}</h2><span>{level.description} · {group.length} {group.length===1?'category':'categories'}</span><ChevronDown size={16} className={`level-chevron ${open?'':'closed'}`}/></button><div className={`level-meter ${level.id.toLowerCase()}`}><div className="level-meter-track" role="progressbar" aria-label={`${level.title} prompts practiced`} aria-valuemin={0} aria-valuemax={total} aria-valuenow={done}><i style={{width:`${total?Math.max(done?4:0,Math.round(done/total*100)):0}%`}}/></div><span className="level-meter-count"><b>{done}</b>/{total} prompts</span><span className="level-meter-pct">{total?Math.round(done/total*100):0}%</span></div>{open&&<div className="category-grid" id={`level-grid-${level.id}`}>{group.map(c=><CategoryCard key={c.id} category={c}/>)}</div>}</section>:null;})}</div>:<div className="category-grid">{filtered.map(c=><CategoryCard key={c.id} category={c}/>)}{!filtered.length&&<div style={{gridColumn:'1 / -1'}}><EmptyState title="Let’s try a different search." description="No categories match these filters. Broaden your search to find your next speaking moment."/></div>}</div>}
 <ChaosChallenge/>
 <PitchRoadmap/>
 </>;
}
