import Link from 'next/link';
import { ArrowUpRight, ArrowRight, AudioLines, Mic, Coffee, Fingerprint, MessageCircle, Brain, BookOpen, Lightbulb, Laptop, Sparkles, BriefcaseBusiness, ChartNoAxesCombined, Globe, MessagesSquare, Users, Flag, Shapes, Shuffle, Zap, LucideIcon, Check } from 'lucide-react';
import { Category } from '@/types';
export const iconMap:Record<string,LucideIcon>={Coffee,Fingerprint,MessageCircle,Brain,BookOpen,Lightbulb,Laptop,Sparkles,BriefcaseBusiness,ChartNoAxesCombined,Globe,MessagesSquare,Users,Flag,Shapes,Shuffle,Zap};
export function Logo({dark=false}:{dark?:boolean}){return <Link href="/" className={`logo ${dark?'logo-light':''}`} aria-label="Vocalis home"><span className="logo-symbol"><AudioLines size={23} strokeWidth={2.5}/></span>vocalis<span className="logo-dot">.</span></Link>;}
export function ButtonLink({href,children,secondary=false,className=''}:{href:string;children:React.ReactNode;secondary?:boolean;className?:string}){return <Link href={href} className={`button ${secondary?'button-secondary':'button-primary'} ${className}`}>{children}</Link>;}
export function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow"><span/>{children}</div>;}
// Rounded so server and client render identical strings (unrounded trig output can differ in the last digits and break hydration).
const waveBars=Array.from({length:53},(_,i)=>({height:`${(12+Math.abs(Math.sin(i*1.7)*Math.cos(i*.37))*67+(i>18&&i<35?20:0)).toFixed(2)}%`,animationDelay:`${(i*.047).toFixed(3)}s`}));
export function Waveform({active=false,light=false}:{active?:boolean;light?:boolean}){return <div className={`waveform ${active?'wave-active':''} ${light?'wave-light':''}`} aria-hidden="true">{waveBars.map((style,i)=><i key={i} style={style}/>)}</div>;}
export function CategoryCard({category,compact=false}:{category:Category;compact?:boolean}){const Icon=iconMap[category.icon]||Mic;return <Link href={`/practice/${category.id}`} className={`category-card ${compact?'compact':''}`}><div className="category-card-top"><span className={`icon-box ${category.color}`}><Icon size={22}/></span><ArrowUpRight className="category-arrow" size={18}/></div><h3>{category.name}</h3><p>{category.description}</p><div className="category-meta"><span className={`difficulty ${category.difficulty.toLowerCase()}`}><i/>{category.difficulty}</span><span>{['random','chaotic'].includes(category.id)?'Surprise prompts':`${category.prompts.length} prompts`}</span></div></Link>;}
export function PageHeading({label,title,description,action}:{label?:string;title:string;description?:string;action?:React.ReactNode}){return <div className="page-heading"><div>{label&&<Eyebrow>{label}</Eyebrow>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>;}
export function StatCard({icon:Icon,label,value,detail,positive=false}:{icon:LucideIcon;label:string;value:string|number;detail:string;positive?:boolean}){return <div className="stat-card"><div className="stat-label"><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small className={positive?'positive':''}>{detail}</small></div>;}
export function ScoreRing({score,size=130}:{score:number;size?:number}){return <div className="score-ring" style={{width:size,height:size}}><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="52" fill="none" stroke="var(--border)" strokeWidth="7"/><circle cx="60" cy="60" r="52" fill="none" stroke="var(--orange)" strokeWidth="7" strokeLinecap="round" strokeDasharray={`${score/100*327} 327`} transform="rotate(-90 60 60)"/></svg><div><strong>{score}</strong><small>/ 100</small></div></div>;}
export function EmptyState({title,description}:{title:string;description:string}){return <div className="empty-state"><span className="icon-box orange"><Mic/></span><h3>{title}</h3><p>{description}</p><ButtonLink href="/practice">Start a session <ArrowRight size={17}/></ButtonLink></div>;}
export function CheckLine({children}:{children:React.ReactNode}){return <span className="check-line"><Check size={14}/>{children}</span>;}
